apiVersion: apps/v1
kind: Deployment
metadata:
  name: books
spec:
  replicas: 2
  selector: 
    matchLabels:
      myevents/app: books
  template:
    metadata:
      labels:
        myevents/app: books
        myevents/tier: api
    spec:
      containers:
      - name: api
        image: myevents/bookservice
        imagePullPolicy: Never
        ports:
        - containerPort: 9191
          name: http
        env:
        - name: MONGO_URL
          value: mongodb://book-db/books
        - name: AMQP_URL
          value: amqp://guest:guest@rabbit-mq:5672/      