apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: book-db
spec:
  serviceName: book-db
  replicas: 1
  selector:
    matchLabels: 
      myevents/app: book-db
  template:
    metadata:
      labels:
        myevents/app: book-db
        myevents/tier: database    
    spec:
      containers: 
      - name: mongo
        image: mongo:3.4.5
        ports:
        - containerPort: 27017
          name: mongo
        volumeMounts:
        - name: database
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata: 
      name: data
      annotations:
        volume.alpha.kubernetes.io/storage-class: standard
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi