apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: event-db
spec:
  serviceName: event-db
  replicas: 1
  selector:
    matchLabels: 
      myevents/app: event-db
  template:
    metadata:
      labels:
        myevents/app: event-db
        myevents/tier: database
    spec:
      containers:
      - name: mongo
        image: mongo:3.4.5
        ports:
        - containerPort: 27017
          name: mongo
        volumeMounts:
        - name: database
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata: 
      name: data
      annotations:
        volume.alpha.kubernetes.io/storage-class: standard
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi              


      