name: Docker test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    
      
    steps:
    - name: set up go
      uses: actions/setup-go@v3
      with: 
        go-version: 1.18
      id: go

    - name: check out go code into the go module directory
      run:  actions/checkout@v3  

    - name: Test
      run: make test