name: Docker test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    service:
      book-db:
        image: mongo
      event-db:
        image: mongo  
      rabbitmq:
        image: rabbitmq:3-mangement
      ports: 
        -  8000:5672
      
    steps:
    - uses: actions/checkout@v3
    - name: set up go
      with: 
        go-version: 1.18
      id: go
    - name: Test
      run: make test